package com.game.enums;


public enum STATE{
		Game(),
		IntroDisplay(),
		GameOver(),
		TestLevel(),
		
		Level(),
		
		LevelOneEasy(),
		LevelTwoEasy(),
		LevelThreeEasy(),
		LevelFourEasy(),
		LevelFiveEasy(),
		LevelSixEasy(),
		LevelSevenEasy(),
		LevelEightEasy(),
		LevelNineEasy(),
		LevelTenEasy(),
		
		LevelOneNormal(),
		LevelTwoNormal(),
		LevelThreeNormal(),
		LevelFourNormal(),
		LevelFiveNormal(),
		LevelSixNormal(),
		LevelSevenNormal(),
		LevelEightNormal(),
		LevelNineNormal(),
		LevelTenNormal(),
		
		LevelOneHard(),
		LevelTwoHard(),
		LevelThreeHard(),
		LevelFourHard(),
		LevelFiveHard(),
		LevelSixHard(),
		LevelSevenHard(),
		LevelEightHard(),
		LevelNineHard(),
		LevelTenHard(),
		
		LevelOneInsane(),
		LevelTwoInsane(),
		LevelThreeInsane(),
		LevelFourInsane(),
		LevelFiveInsane(),
		LevelSixInsane(),
		LevelSevenInsane(),
		LevelEightInsane(),
		LevelNineInsane(),
		LevelTenInsane(),
		
		Map(),
		Map1(),
		Map2(),
		Map3(),
		Map4(),
		Map5(),
		Map6(),
		Map7(),
		Map8(),
		Map9(),
		Map10(),
		Map11(),
		
		MainMenu(),
		Controls(),
		Player1HighScores(),
		Player2HighScores(),
		Player3HighScores(),
		NewHighScorePlayer1(),
		NewHighScorePlayer2(),
		NewHighScorePlayer3(),
		Player1Info(),
		Player2Info(),
		Player3Info(),
		HighScores(),
		Pause(),
		CharacterSelect(),
		PatchNotes(),
		MusicSettings(),
		Info(),
		SkillSelect(),
		SmallSettings(),
		ContinueMenu(),
		LoadingScreen(),
		NewGame(),
		SkillPointSelect(),
		MainSettings(), ;
};
